# Configuration for the Telegram bot.
telegram:
  # Token provided by Telegram's BotFather for authentication.
  token: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11

  # Bot administrators
  admins: [1234567890]

  # Ignore all messages, but keep handling button callbacks, poll answers, etc.
  # Useful when migrating the bot to another bot account.
  passive_mode: false

  # Configuration for specific chat threads.
  chats:
    # List of chats considered as residents-only.
    # User residency status status is added/revoked by joining/leaving these
    # chats by 'resident_tracker' module.
    # The welcome message is sent when joining the first chat in this list.
    residential:
      - -1001234567890
      - -1001234567890

    # List of threads for 'borrowed_items' module.
    borrowed_items:
      - { chat: -1001234567890, thread: 123 }

    # Thread for the 'dashboard' module.
    dashboard: { chat: -1001234567890, thread: 123 }

    # The ID of the backup message channel for the debates module.
    # Bot maintainer is supposed to create private channel and add bot into it.
    forward_channel: -1001234567890

    # Forward pinned messages from specified source chats to the target channel.
    forward_pins:
      - from: -1001234567890
        to: -1001234567890
        ignore_threads: [123]

    # Thread for the 'needs' module.
    needs: { chat: -1001234567890, thread: 123 }

    # Thread for the 'mac_monitoring' module.
    mac_monitoring: { chat: -1001234567890, thread: 456 }

    # Thread for the 'ask_to_visit' module.
    ask_to_visit: { chat: -1001234567890, thread: 789 }

    # List of chats considered as resident-owned. Used to print an admin table.
    resident_owned:
      - { id: -1001234567890, internal: true }

    # Chat to push Wiki.js update notifications.
    wikijs_updates: { chat: -1001234567890, thread: 123 }

# Address to to provide HTTP API on.
server_addr: 127.0.0.1:8080

# Configuration to access external services.
services:
  # Microtik REST API is used to get list of MAC addresses of the connected
  # devices.
  mikrotik:
    host: 10.0.0.1
    username: SECRET
    password: SECRET

  # Home Assistant configuration.
  # FIXME: currently unused
  home_assistant:
    host: homeassistant.lo.f0rth.space
    token: SECRET

  # Wiki.js GraphQL API is used to monitor recent page updates.
  wikijs:
    url: https://wiki.f0rth.space
    # Bearer token for authentication. Could be extracted from either browser
    # console, or here: https://wiki.f0rth.space/a/api.
    token: SECRET
    # A path to the page containg welcome message, for the 'welcome' module.
    welcome_message_page: /en/residents/welcome-message
    # A path to the page contaning dashboard text, for the 'dashboard' module.
    dashboard_page: /en/residents/topic-index

  # OpenAI API configuration.
  openai:
    api_key: SECRET
    # Use stub logic instead of OpenAI API. Useful for local testing.
    disable: false
